export const cursos = [
  {
    id: 1,
    titulo: 'Desenvolvimento Web Full Stack',
    descricao: 'HTML, CSS, JavaScript, React, Node.js e bancos de dados. Do zero ao deploy em produção.',
    duracao: '6 meses',
    nivel: 'Iniciante',
    vagas: 30,
    preco: 'R$ 197/mês',
    icon: '⚡',
    tag: 'Mais popular',
    topicos: ['React & Next.js', 'Node.js & Express', 'PostgreSQL', 'Deploy na nuvem'],
  },
  {
    id: 2,
    titulo: 'Python para Dados & IA',
    descricao: 'Pandas, NumPy, Machine Learning com scikit-learn e introdução a LLMs com Python.',
    duracao: '5 meses',
    nivel: 'Intermediário',
    vagas: 25,
    preco: 'R$ 197/mês',
    icon: '🧠',
    tag: 'Novo',
    topicos: ['Python avançado', 'Pandas & NumPy', 'Machine Learning', 'APIs de IA'],
  },
  {
    id: 3,
    titulo: 'UI/UX Design System',
    descricao: 'Figma, design de interfaces, pesquisa com usuários e prototipação de alta fidelidade.',
    duracao: '4 meses',
    nivel: 'Iniciante',
    vagas: 20,
    preco: 'R$ 147/mês',
    icon: '🎨',
    tag: null,
    topicos: ['Figma avançado', 'Design System', 'Prototipação', 'UX Research'],
  },
  {
    id: 4,
    titulo: 'DevOps & Cloud Engineering',
    descricao: 'Docker, Kubernetes, CI/CD pipelines, AWS e infraestrutura como código com Terraform.',
    duracao: '5 meses',
    nivel: 'Avançado',
    vagas: 15,
    preco: 'R$ 247/mês',
    icon: '☁️',
    tag: 'Alta demanda',
    topicos: ['Docker & K8s', 'AWS / GCP', 'CI/CD', 'Terraform'],
  },
  {
    id: 5,
    titulo: 'Mobile com React Native',
    descricao: 'Crie apps iOS e Android com React Native, Expo e integração com APIs REST.',
    duracao: '4 meses',
    nivel: 'Intermediário',
    vagas: 20,
    preco: 'R$ 197/mês',
    icon: '📱',
    tag: null,
    topicos: ['React Native', 'Expo', 'Navigation', 'Push Notifications'],
  },
  {
    id: 6,
    titulo: 'Segurança e Ethical Hacking',
    descricao: 'Fundamentos de cibersegurança, pentest, OWASP Top 10 e preparação para certificações.',
    duracao: '6 meses',
    nivel: 'Intermediário',
    vagas: 15,
    preco: 'R$ 247/mês',
    icon: '🔐',
    tag: null,
    topicos: ['Pentest', 'OWASP', 'Redes', 'CTF Challenges'],
  },
]

export const depoimentos = [
  {
    id: 1,
    nome: 'Camila Souza',
    cargo: 'Frontend Developer — Nubank',
    texto: 'Em 7 meses saí de caixa de supermercado para dev júnior no Nubank. O suporte da comunidade e a qualidade das aulas foram decisivos. Recomendo demais.',
    avatar: 'CS',
    estrelas: 5,
  },
  {
    id: 2,
    nome: 'Rafael Mendes',
    cargo: 'Data Analyst — iFood',
    texto: 'Já tinha noção de Python mas o curso de Dados me elevou de nível. Aprendi a construir pipelines reais. Fui promovido três meses depois de terminar.',
    avatar: 'RM',
    estrelas: 5,
  },
  {
    id: 3,
    nome: 'Juliana Costa',
    cargo: 'UX Designer — Creditas',
    texto: 'A didática é incrível. Passei de designer gráfico para UX em menos de um ano. Os projetos práticos do curso foram o que me diferenciaram no processo seletivo.',
    avatar: 'JC',
    estrelas: 5,
  },
  {
    id: 4,
    nome: 'Lucas Ferreira',
    cargo: 'Backend Engineer — PicPay',
    texto: 'Melhor investimento que já fiz na minha carreira. Conteúdo atualizado, mentores presentes e uma rede de alunos que vale ouro.',
    avatar: 'LF',
    estrelas: 5,
  },
]

export const faqs = [
  {
    id: 1,
    pergunta: 'Preciso ter conhecimento prévio em programação?',
    resposta: 'Depende do curso. Os cursos marcados como "Iniciante" não exigem nenhum conhecimento prévio — começamos do zero mesmo. Já os cursos Intermediários e Avançados indicam os pré-requisitos na página do curso.',
  },
  {
    id: 2,
    pergunta: 'As aulas são ao vivo ou gravadas?',
    resposta: 'Temos um modelo híbrido: as aulas teóricas são gravadas (assista quando quiser), e realizamos encontros ao vivo semanais para tirar dúvidas, resolver desafios e fazer code review com os instrutores.',
  },
  {
    id: 3,
    pergunta: 'Por quanto tempo tenho acesso ao conteúdo?',
    resposta: 'Acesso vitalício ao conteúdo do seu curso, incluindo todas as atualizações futuras. Qualquer material novo adicionado ao curso estará disponível para você automaticamente.',
  },
  {
    id: 4,
    pergunta: 'Existe garantia de emprego?',
    resposta: 'Não prometemos emprego, mas oferecemos suporte ativo à carreira: revisão de currículo, mock interviews, indicações para empresas parceiras e acesso à nossa rede de alumni com mais de 2.400 profissionais contratados.',
  },
  {
    id: 5,
    pergunta: 'Emitem certificado ao final?',
    resposta: 'Sim! Certificado digital com validação em blockchain, reconhecido pelas principais empresas de tecnologia do Brasil. Você também recebe um selo de conclusão para exibir no LinkedIn.',
  },
  {
    id: 6,
    pergunta: 'Posso parcelar a matrícula?',
    resposta: 'Sim. Aceitamos parcelamento em até 12x sem juros no cartão de crédito, além de boleto bancário e Pix. Entre em contato conosco para opções de bolsa e desconto para grupos.',
  },
]

export const diferenciais = [
  {
    icon: '🎯',
    titulo: 'Projetos reais',
    descricao: 'Cada módulo termina com um projeto que vai direto para o seu portfólio — sem exercícios artificiais.',
  },
  {
    icon: '👨‍🏫',
    titulo: 'Mentores do mercado',
    descricao: 'Nossos instrutores trabalham em empresas como Nubank, Mercado Livre e Google. Aprenda com quem vive isso.',
  },
  {
    icon: '🤝',
    titulo: 'Comunidade ativa',
    descricao: 'Discord exclusivo, study groups, hackathons mensais e networking com mais de 8 mil alunos.',
  },
  {
    icon: '♾️',
    titulo: 'Conteúdo atualizado',
    descricao: 'O mercado muda rápido. Nossas trilhas são revisadas trimestralmente para acompanhar as tendências.',
  },
  {
    icon: '📊',
    titulo: 'Suporte à carreira',
    descricao: 'Mock interviews, revisão de currículo, LinkedIn e acesso à bolsa de talentos com 200+ empresas parceiras.',
  },
  {
    icon: '🔄',
    titulo: 'Aprendizado flexível',
    descricao: 'Estude no seu ritmo. Aulas gravadas disponíveis 24/7, com suporte por chat em horário comercial.',
  },
]
